import { useState, type FormEvent, type ReactNode } from "react";
import { Barcode, CalendarDays, CheckCircle2, DollarSign, PackagePlus, Save, Sparkles, Warehouse, X } from "lucide-react";
import type { CatalogProduct } from "../../types/operations";

export interface QuickProductFormData {
  barcode: string; sku: string; name: string; brand: string; category: string;
  costPrice: string; salePrice: string; minStockGlobal: string; shelfLifeDays: string;
  initialStockCD: string; unit: string; isPerishable: boolean;
}
const initialForm: QuickProductFormData = { barcode: "", sku: "", name: "", brand: "", category: "Bebidas", costPrice: "", salePrice: "", minStockGlobal: "30", shelfLifeDays: "180", initialStockCD: "0", unit: "un", isPerishable: false };
const inputClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";

export function QuickProductForm({ onClose, onSave }: { onClose: () => void; onSave: (data: QuickProductFormData) => Promise<void> }) {
  const [form, setForm] = useState(initialForm); const [scanning, setScanning] = useState(false); const [autoFilled, setAutoFilled] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (patch: Partial<QuickProductFormData>) => setForm((current) => ({ ...current, ...patch }));
  const cost = Number(form.costPrice.replace(",", ".")) || 0; const sale = Number(form.salePrice.replace(",", ".")) || 0;
  const margin = sale > 0 ? ((sale - cost) / sale) * 100 : 0; const profit = Math.max(0, sale - cost);
  const simulateScan = () => { setScanning(true); window.setTimeout(() => { setForm((current) => ({ ...current, barcode: "789123456789", sku: "BEB-COC-350", name: "Coca-Cola Original 350ml", brand: "The Coca-Cola Company", category: "Bebidas", costPrice: "2,80", salePrice: "5,00", minStockGlobal: "120", shelfLifeDays: "180", initialStockCD: "240", unit: "un", isPerishable: false })); setScanning(false); setAutoFilled(true); }, 500); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); try { await onSave(form); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o produto."); } finally { setSaving(false); } };
  return <section className="overflow-hidden rounded-xl border border-blue-200 bg-white shadow-sm" aria-labelledby="quick-product-title">
    <header className="flex items-start justify-between gap-4 border-b border-slate-100 bg-slate-50/70 px-5 py-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-600 p-2.5 text-white"><PackagePlus className="h-5 w-5"/></span><div><div className="flex flex-wrap items-center gap-2"><h2 id="quick-product-title" className="font-bold text-slate-900">Cadastro rápido de produto</h2><span className="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 text-[10px] font-bold uppercase text-blue-700">Entrada expressa</span></div><p className="mt-1 text-sm text-slate-500">Informe os dados essenciais do produto e sua entrada inicial no CD.</p></div></div><button type="button" onClick={onClose} aria-label="Fechar cadastro rápido" title="Fechar" className="rounded-lg p-2 text-slate-400 hover:bg-slate-200 hover:text-slate-700"><X className="h-5 w-5"/></button></header>
    <form onSubmit={(event) => void submit(event)} className="space-y-5 p-5">
      <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-700"><Barcode className="h-4 w-4 text-blue-600"/>Código de barras e SKU</h3><button type="button" onClick={simulateScan} disabled={scanning} className="inline-flex items-center gap-1.5 rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-700 hover:bg-blue-50 disabled:opacity-50"><Sparkles className="h-3.5 w-3.5"/>{scanning ? "Lendo…" : "Simular leitura EAN"}</button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Código de barras (EAN / GTIN) *"><input required value={form.barcode} onChange={(e) => update({ barcode: e.target.value })} className={`${inputClass} font-mono`} placeholder="Ex.: 789123456789"/></Field><Field label="Código SKU interno"><input value={form.sku} onChange={(e) => update({ sku: e.target.value })} className={`${inputClass} font-mono`} placeholder="Ex.: BEB-COC-350"/></Field></div>{autoFilled && <p className="mt-3 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Dados preenchidos pela simulação de leitura EAN.</p>}</div>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Nome do produto *" className="sm:col-span-2"><input required value={form.name} onChange={(e) => update({ name: e.target.value })} className={inputClass} placeholder="Nome completo"/></Field><Field label="Marca / fabricante"><input value={form.brand} onChange={(e) => update({ brand: e.target.value })} className={inputClass} placeholder="Marca"/></Field><Field label="Categoria"><select value={form.category} onChange={(e) => update({ category: e.target.value })} className={inputClass}><option>Bebidas</option><option>Perecíveis</option><option>Snacks e Doces</option><option>Laticínios</option><option>Outros</option></select></Field><Field label="Unidade de medida"><select value={form.unit} onChange={(e) => update({ unit: e.target.value })} className={inputClass}><option value="un">Unidade (un)</option><option value="pct">Pacote (pct)</option><option value="cx">Caixa (cx)</option><option value="kg">Quilograma (kg)</option></select></Field><label className="flex items-center gap-2 self-end pb-2 text-sm text-slate-700"><input type="checkbox" checked={form.isPerishable} onChange={(e) => update({ isPerishable: e.target.checked })} className="h-4 w-4 accent-blue-600"/>Produto perecível</label></div>
      <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"><h3 className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-700"><DollarSign className="h-4 w-4 text-emerald-600"/>Precificação e margem</h3><div className="grid gap-3 sm:grid-cols-3"><Field label="Preço de custo (R$)"><input inputMode="decimal" value={form.costPrice} onChange={(e) => update({ costPrice: e.target.value })} className={`${inputClass} font-mono`} placeholder="0,00"/></Field><Field label="Preço de venda (R$) *"><input required inputMode="decimal" value={form.salePrice} onChange={(e) => update({ salePrice: e.target.value })} className={`${inputClass} font-mono`} placeholder="0,00"/></Field><div><span className="mb-1 block text-xs font-semibold text-slate-500">Margem estimada</span><div className="flex h-[38px] items-center justify-between rounded-lg border border-slate-200 bg-white px-3 text-sm"><b className="text-emerald-700">{margin.toFixed(1)}%</b><span className="text-xs text-slate-400">R$ {profit.toFixed(2).replace(".", ",")}/un</span></div></div></div></div>
      <div className="grid gap-3 sm:grid-cols-3"><Field label={<span className="flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5"/>Shelf life (dias) *</span>}><input required min="1" type="number" value={form.shelfLifeDays} onChange={(e) => update({ shelfLifeDays: e.target.value, isPerishable: Number(e.target.value) <= 30 })} className={`${inputClass} font-mono`}/></Field><Field label="Estoque mínimo global"><input min="0" type="number" value={form.minStockGlobal} onChange={(e) => update({ minStockGlobal: e.target.value })} className={`${inputClass} font-mono`}/></Field><Field label="Quantidade inicial no CD"><input min="0" type="number" value={form.initialStockCD} onChange={(e) => update({ initialStockCD: e.target.value })} className={`${inputClass} font-mono`}/></Field></div>
      {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="flex items-center gap-2 text-xs text-slate-500"><Warehouse className="h-4 w-4 text-blue-600"/>Produto e estoque inicial vinculados ao <b>CD</b>.</p><div className="flex gap-2"><button type="button" onClick={onClose} className="rounded-lg bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-200">Cancelar</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><Save className="h-4 w-4"/>{saving ? "Salvando…" : "Salvar produto"}</button></div></footer>
    </form>
  </section>;
}

function Field({ label, children, className = "" }: { label: ReactNode; children: ReactNode; className?: string }) { return <label className={`block text-xs font-semibold text-slate-500 ${className}`}><span className="mb-1 block">{label}</span>{children}</label>; }
export function quickFormToProduct(data: QuickProductFormData, id: string): CatalogProduct {
  const price = (value: string) => Number(value.replace(",", ".")) || 0;
  return { id, sku: data.sku || data.barcode, barcode: data.barcode, name: data.name, brand: data.brand, category: data.category, costPrice: price(data.costPrice), salePrice: price(data.salePrice), minimumStock: Number(data.minStockGlobal) || 0, shelfLifeDays: Number(data.shelfLifeDays) || 0, locationsCount: 1, status: "ACTIVE" };
}
