import { ArrowLeftRight, Eye, ShoppingCart } from "lucide-react";
import type { StockListItem } from "../../types/stock";

const dateFormat = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "UTC" });
export function StockTable({ items, loading }: { items: StockListItem[]; loading: boolean }) {
  if (loading) return <div className="p-12 text-center text-sm text-slate-500">Carregando estoque...</div>;
  if (!items.length) return <div className="p-12 text-center"><p className="font-semibold text-slate-700">Nenhum item encontrado</p><p className="mt-1 text-sm text-slate-400">Altere os filtros ou a busca para ver outros produtos.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50/80 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Código de barras</th><th className="px-3 py-3">Produto / marca</th><th className="px-3 py-3">Categoria</th><th className="px-3 py-3">Local</th><th className="px-3 py-3 text-right">Quantidade</th><th className="px-3 py-3 text-right">Mínimo</th><th className="px-3 py-3">Próxima validade</th><th className="px-3 py-3">Status</th><th className="px-4 py-3 text-center">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => { const status = item.status === "NORMAL" ? { label: "Normal", cls: "bg-emerald-50 text-emerald-700" } : item.status === "LOW" ? { label: "Estoque baixo", cls: "bg-amber-50 text-amber-700" } : { label: "Sem estoque", cls: "bg-red-50 text-red-700" }; return <tr key={item.stock.id} className="hover:bg-slate-50/60"><td className="px-4 py-3 font-mono text-xs text-slate-600">{item.product.barcode}</td><td className="px-3 py-3"><p className="font-semibold text-slate-800">{item.product.name}</p><p className="text-xs text-slate-400">{item.product.brand ?? "Sem marca"} · Lote {item.batch.batchCode}</p></td><td className="px-3 py-3 text-slate-600">{item.category.name}</td><td className="px-3 py-3 text-slate-600">{item.location.name}</td><td className="px-3 py-3 text-right font-mono font-bold">{item.stock.quantity} {item.product.unit}</td><td className="px-3 py-3 text-right font-mono text-slate-500">{item.product.minimumStock ?? "—"}</td><td className="px-3 py-3">{item.batch.expirationDate ? <><p className="text-slate-700">{dateFormat.format(new Date(`${item.batch.expirationDate.slice(0, 10)}T00:00:00Z`))}</p><p className={`text-xs ${item.daysUntilExpiry !== null && item.daysUntilExpiry <= 7 ? "font-semibold text-red-600" : "text-slate-400"}`}>{item.daysUntilExpiry === 0 ? "Vence hoje" : item.daysUntilExpiry !== null && item.daysUntilExpiry < 0 ? "Vencido" : `${item.daysUntilExpiry} dias restantes`}</p></> : <span className="text-slate-400">Sem validade</span>}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${status.cls}`}>{status.label}</span></td><td className="px-4 py-3"><div className="flex justify-center gap-1 text-slate-400"><button type="button" title="Ver detalhes" aria-label={`Ver ${item.product.name}`} className="rounded p-1.5 hover:bg-slate-100 hover:text-slate-700"><Eye className="h-4 w-4" /></button><button type="button" title={item.status === "OUT_OF_STOCK" ? "Solicitar reposição" : "Transferir"} aria-label={item.status === "OUT_OF_STOCK" ? "Solicitar reposição" : "Transferir estoque"} className="rounded p-1.5 hover:bg-slate-100 hover:text-blue-600">{item.status === "OUT_OF_STOCK" ? <ShoppingCart className="h-4 w-4" /> : <ArrowLeftRight className="h-4 w-4" />}</button></div></td></tr>; })}</tbody></table></div>;
}
