import { Barcode, Search, SlidersHorizontal } from "lucide-react";
import type { Category, Location } from "../../types/entities";
import type { ExpiryWindow, StockFilters as Filters, StockStatus } from "../../types/stock";

interface Props { filters: Filters; locations: Location[]; categories: Category[]; onChange: (filters: Filters) => void }
export function StockFilters({ filters, locations, categories, onChange }: Props) {
  const update = (patch: Partial<Filters>) => onChange({ ...filters, ...patch, page: 1 });
  return <section className="space-y-4 rounded-xl border border-slate-200/80 bg-white p-4 shadow-xs" aria-label="Filtros de estoque">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={filters.search} onChange={(event) => update({ search: event.target.value })} placeholder="Buscar por produto, marca ou código de barras" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-10 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" aria-label="Buscar produtos" /><Barcode className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /></div><label className="flex shrink-0 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={filters.lowStockOnly} onChange={(event) => update({ lowStockOnly: event.target.checked })} className="h-4 w-4 rounded border-slate-300 accent-blue-600" />Somente estoque baixo</label></div>
    <div className="grid grid-cols-1 gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold text-slate-500">Local<select value={filters.locationId} onChange={(event) => update({ locationId: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700"><option value="ALL">Todos os locais</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Categoria<select value={filters.categoryId} onChange={(event) => update({ categoryId: event.target.value })} className="mt-1 block w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700"><option value="ALL">Todas as categorias</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Status<select value={filters.status} onChange={(event) => update({ status: event.target.value as StockStatus | "ALL" })} className="mt-1 block w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700"><option value="ALL">Todos os status</option><option value="NORMAL">Normal</option><option value="LOW">Estoque baixo</option><option value="OUT_OF_STOCK">Sem estoque</option></select></label><label className="text-xs font-semibold text-slate-500">Validade<select value={filters.expiry} onChange={(event) => update({ expiry: event.target.value as ExpiryWindow })} className="mt-1 block w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700"><option value="ALL">Todas as validades</option><option value="7">Até 7 dias</option><option value="15">Até 15 dias</option><option value="30">Até 30 dias</option><option value="SAFE">Mais de 30 dias</option></select></label></div><div className="flex items-center gap-1 text-xs text-slate-400"><SlidersHorizontal className="h-3.5 w-3.5" />Os filtros são combinados na busca.</div>
  </section>;
}
