import { useEffect, useState } from "react";
import { MapPin, Plus, RefreshCw, Store, Warehouse } from "lucide-react";
import { operationsService } from "../services/operations.service";
import type { StoreLocation } from "../types/operations";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
export default function Locais() {
  const [items,setItems]=useState<StoreLocation[]>([]); useEffect(()=>{void operationsService.listLocations().then(setItems);},[]);
  return <div className="min-w-0 space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Rede de distribuição</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Locais e pontos de venda</h1><p className="mt-1 text-sm text-slate-500">Visão consolidada do CD, mercadinhos e vending machines.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Cadastrar local</button></header>
    <div className="grid gap-4 sm:grid-cols-3"><Stat label="Locais cadastrados" value={String(items.length)}/><Stat label="Ativos" value={String(items.filter(x=>x.status==="ACTIVE").length)}/><Stat label="Valor em estoque" value={money.format(items.reduce((s,x)=>s+x.stockValue,0))}/></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((loc)=><article key={loc.id} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-xs"><div className="flex items-start justify-between"><span className="rounded-lg bg-blue-50 p-2 text-blue-700">{loc.type==="WAREHOUSE"?<Warehouse className="h-5 w-5"/>:<Store className="h-5 w-5"/>}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${loc.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{loc.status==="ACTIVE"?"Ativo":"Manutenção"}</span></div><div><h2 className="text-lg font-bold text-slate-900">{loc.name}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="h-4 w-4"/>{loc.address}</p></div><div className="grid grid-cols-2 gap-3 border-y border-slate-100 py-3"><Info label="SKUs ativos" value={loc.skuCount.toLocaleString("pt-BR")}/><Info label="Valor em estoque" value={money.format(loc.stockValue)}/></div><div><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Capacidade utilizada</span><b>{loc.capacity}%</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${loc.capacity}%`}}/></div></div><p className="flex items-center gap-1 text-xs text-slate-400"><RefreshCw className="h-3 w-3"/>Sincronizado {loc.lastSync}</p></article>)}</section></div>;
}
function Stat({label,value}:{label:string;value:string}){return <article className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>}
function Info({label,value}:{label:string;value:string|number}){return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>}
