import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowDownToLine, ArrowLeftRight, ArrowUpFromLine, ClipboardList, Plus, Search } from "lucide-react";
import { operationsService } from "../services/operations.service";
import type { MovementRecord } from "../types/operations";
const labels = { ENTRY: "Entrada", EXIT: "Saída", TRANSFER: "Transferência", ADJUSTMENT: "Ajuste" };
const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" });
export default function Movimentacoes() {
  const [items, setItems] = useState<MovementRecord[]>([]); const [search, setSearch] = useState(""); const [type, setType] = useState("ALL");
  useEffect(() => { void operationsService.listMovements().then(setItems); }, []);
  const filtered = useMemo(() => items.filter((m) => (type === "ALL" || m.type === type) && `${m.productName} ${m.sku} ${m.batch}`.toLowerCase().includes(search.toLowerCase())), [items, type, search]);
  return <div className="min-w-0 space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Rastreabilidade · CD e unidades</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Movimentações de estoque</h1><p className="mt-1 text-sm text-slate-500">Acompanhe entradas, saídas, transferências e ajustes por lote.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Nova movimentação</button></header>
    <div className="grid gap-4 sm:grid-cols-4"><MoveMetric title="Movimentações" value={String(items.length)} icon={<ClipboardList/>}/><MoveMetric title="Entradas" value={String(items.filter(x=>x.type==="ENTRY").length)} icon={<ArrowDownToLine/>}/><MoveMetric title="Transferências" value={String(items.filter(x=>x.type==="TRANSFER").length)} icon={<ArrowLeftRight/>}/><MoveMetric title="Pendentes" value={String(items.filter(x=>x.status==="PENDING").length)} icon={<ArrowUpFromLine/>}/></div>
    <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto, SKU ou lote" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="ALL">Todos os tipos</option>{Object.entries(labels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Data e hora","Tipo","Produto / lote","Quantidade","Origem","Destino","Responsável","Status"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(m=><tr key={m.id}><td className="px-3 py-3">{date.format(new Date(m.date))}</td><td className="px-3 py-3">{labels[m.type]}</td><td className="px-3 py-3 font-medium">{m.productName}<p className="text-xs text-slate-400">{m.sku} · {m.batch}</p></td><td className="px-3 py-3 font-mono">{m.quantity}</td><td className="px-3 py-3">{m.origin ?? "—"}</td><td className="px-3 py-3">{m.destination ?? "—"}</td><td className="px-3 py-3">{m.user}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${m.status==="COMPLETED"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{m.status==="COMPLETED"?"Concluída":"Pendente"}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-sm text-slate-500">Nenhuma movimentação encontrada.</p>}</div></section></div>;
}
function MoveMetric({title,value,icon}:{title:string;value:string;icon:ReactNode}) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-xs font-semibold uppercase text-slate-500">{title}<span className="h-4 w-4 text-blue-600">{icon}</span></div><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>; }
