import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { ArrowDownToLine, ArrowLeftRight, ArrowUpFromLine, ClipboardList, Plus, Search } from "lucide-react";
import { operationsService } from "../services/operations.service";
import { useLocationFilter } from "../contexts/LocationFilterContext";
import type { MovementRecord } from "../types/operations";

const labels: Record<MovementRecord["type"], string> = { ENTRY: "Entrada", EXIT: "Saída", TRANSFER: "Transferência", ADJUSTMENT: "Ajuste" };
const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" });
const field = "mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2 text-sm";

export default function Movimentacoes() {
  const [items, setItems] = useState<MovementRecord[]>([]); const [search, setSearch] = useState(""); const [type, setType] = useState("ALL"); const [formOpen, setFormOpen] = useState(false); const [notice, setNotice] = useState("");
  const { matchesLocation } = useLocationFilter();
  useEffect(() => { void operationsService.listMovements().then(setItems); }, []);
  const filtered = useMemo(() => items.filter((m) => matchesLocation(m.origin) || matchesLocation(m.destination)).filter((m) => (type === "ALL" || m.type === type) && `${m.productName} ${m.sku} ${m.batch}`.toLowerCase().includes(search.toLowerCase())), [items, type, search, matchesLocation]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const record = await operationsService.createMovement({ type: data.get("type") as MovementRecord["type"], productName: String(data.get("productName")), sku: String(data.get("sku")), quantity: Number(data.get("quantity")), origin: String(data.get("origin") || "") || null, destination: String(data.get("destination") || "") || null, batch: String(data.get("batch") || "—") }); setItems((current) => [record, ...current]); setFormOpen(false); setNotice("Movimentação registrada."); };
  return <div className="min-w-0 space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Rastreabilidade · CD e unidades</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Movimentações de estoque</h1><p className="mt-1 text-sm text-slate-500">Acompanhe entradas, saídas, transferências e ajustes por lote.</p></div><button type="button" onClick={() => setFormOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Nova movimentação</button></header>
    {notice && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    {formOpen && <form onSubmit={(event) => void create(event)} className="grid gap-3 rounded-xl border border-blue-200 bg-white p-4 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-500">Tipo<select name="type" className={field}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Produto<input required name="productName" placeholder="Nome do produto" className={field}/></label><label className="text-xs font-semibold text-slate-500">SKU<input required name="sku" placeholder="SKU" className={field}/></label><label className="text-xs font-semibold text-slate-500">Quantidade<input required name="quantity" type="number" min="1" className={field}/></label><label className="text-xs font-semibold text-slate-500">Origem<input name="origin" placeholder="CD" className={field}/></label><label className="text-xs font-semibold text-slate-500">Destino<input name="destination" placeholder="Unidade" className={field}/></label><label className="text-xs font-semibold text-slate-500">Lote<input name="batch" className={field}/></label><div className="flex items-end justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setFormOpen(false)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">Cancelar</button><button className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Registrar movimentação</button></div></form>}
    <div className="grid gap-4 sm:grid-cols-4"><MoveMetric title="Movimentações" value={String(filtered.length)} icon={<ClipboardList/>}/><MoveMetric title="Entradas" value={String(filtered.filter(x=>x.type==="ENTRY").length)} icon={<ArrowDownToLine/>}/><MoveMetric title="Transferências" value={String(filtered.filter(x=>x.type==="TRANSFER").length)} icon={<ArrowLeftRight/>}/><MoveMetric title="Pendentes" value={String(filtered.filter(x=>x.status==="PENDING").length)} icon={<ArrowUpFromLine/>}/></div>
    <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto, SKU ou lote" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="ALL">Todos os tipos</option>{Object.entries(labels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Data e hora","Tipo","Produto / lote","Quantidade","Origem","Destino","Responsável","Status"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(m=><tr key={m.id}><td className="px-3 py-3">{date.format(new Date(m.date))}</td><td className="px-3 py-3">{labels[m.type]}</td><td className="px-3 py-3 font-medium">{m.productName}<p className="text-xs text-slate-400">{m.sku} · {m.batch}</p></td><td className="px-3 py-3 font-mono">{m.quantity}</td><td className="px-3 py-3">{m.origin ?? "—"}</td><td className="px-3 py-3">{m.destination ?? "—"}</td><td className="px-3 py-3">{m.user}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${m.status==="COMPLETED"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{m.status==="COMPLETED"?"Concluída":"Pendente"}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-sm text-slate-500">Nenhuma movimentação encontrada.</p>}</div></section></div>;
}
function MoveMetric({title,value,icon}:{title:string;value:string;icon:ReactNode}) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-xs font-semibold uppercase text-slate-500">{title}<span className="h-4 w-4 text-blue-600">{icon}</span></div><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>; }
