import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Download, Package, Plus, Search } from "lucide-react";
import { operationsService } from "../services/operations.service";
import type { CatalogProduct } from "../types/operations";
import { QuickProductForm, quickFormToProduct, type QuickProductFormData } from "../components/products/QuickProductForm";
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export default function Produtos() {
  const [items, setItems] = useState<CatalogProduct[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState("ALL");
  const [quickFormOpen, setQuickFormOpen] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { void operationsService.listProducts().then(setItems); }, []);
  const filtered = useMemo(() => items.filter((p) => (category === "ALL" || p.category === category) && `${p.name} ${p.sku} ${p.barcode}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))), [items, search, category]);
  const categories = [...new Set(items.map((p) => p.category))];
  const saveProduct = async (data: QuickProductFormData) => {
    const product = quickFormToProduct(data, "pending");
    const saved = await operationsService.createProduct(product, Number(data.initialStockCD) || 0);
    setItems((current) => [saved, ...current]);
    setQuickFormOpen(false);
    setNotice(`Produto “${saved.name}” cadastrado com sucesso.`);
  };
  return <div className="min-w-0 space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Catálogo master · {items.length} produtos</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Produtos</h1><p className="mt-1 text-sm text-slate-500">Gerencie o catálogo, códigos de barras, custos e regras PEPS.</p></div><div className="flex gap-2"><button type="button" onClick={() => { const csv = ["SKU;Código de barras;Produto;Categoria;Custo;Venda", ...filtered.map((p) => [p.sku,p.barcode,p.name,p.category,p.costPrice,p.salePrice].join(";"))].join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); a.download = "produtos.csv"; a.click(); URL.revokeObjectURL(a.href); }} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><Download className="h-4 w-4"/>Exportar</button><button type="button" onClick={() => { setQuickFormOpen(true); setNotice(null); }} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Novo produto</button></div></header>
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Package className="h-4 w-4"/>} label="Produtos cadastrados" value={String(items.length)} /><Metric label="Categorias" value={String(categories.length)} /><Metric label="Itens em revisão" value={String(items.filter((p) => p.status === "REVIEW").length)} /></div>
    {quickFormOpen && <QuickProductForm onClose={() => setQuickFormOpen(false)} onSave={saveProduct} />}
    {notice && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input aria-label="Buscar produtos" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nome, SKU ou código de barras" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm"/></div><select aria-label="Categoria" value={category} onChange={(e) => setCategory(e.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="ALL">Todas as categorias</option>{categories.map((x) => <option key={x}>{x}</option>)}</select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{["SKU / EAN","Produto / Marca","Categoria","Custo","Venda","Margem","Shelf life","Status"].map((x) => <th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((p) => <tr key={p.id}><td className="px-3 py-3 font-mono text-xs">{p.sku}<p className="text-slate-400">{p.barcode}</p></td><td className="px-3 py-3 font-medium">{p.name}<p className="text-xs text-slate-400">{p.brand}</p></td><td className="px-3 py-3">{p.category}</td><td className="px-3 py-3 text-right">{brl.format(p.costPrice)}</td><td className="px-3 py-3 text-right">{brl.format(p.salePrice)}</td><td className="px-3 py-3 text-right text-emerald-700">{(((p.salePrice-p.costPrice)/p.salePrice)*100).toFixed(1)}%</td><td className="px-3 py-3 text-center">{p.shelfLifeDays} dias</td><td className="px-3 py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{p.status === "ACTIVE" ? "Ativo" : p.status === "REVIEW" ? "Em revisão" : "Inativo"}</span></td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-sm text-slate-500">Nenhum produto encontrado.</p>}</div></section>
  </div>;
}
function Metric({ icon, label, value }: { icon?: ReactNode; label: string; value: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between text-xs font-semibold uppercase text-slate-500">{label}<span className="text-blue-600">{icon}</span></div><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>; }
