import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, Download, FileText, ShieldCheck, TrendingUp } from "lucide-react";
import { operationsService } from "../services/operations.service";
import type { ReportCard } from "../types/operations";
export default function Relatorios() {
  const [items,setItems]=useState<ReportCard[]>([]); useEffect(()=>{void operationsService.listReports().then(setItems);},[]);
  return <div className="min-w-0 space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Centro de dados e conformidade</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Relatórios e inteligência logística</h1><p className="mt-1 text-sm text-slate-500">Indicadores de inventário, validade, vendas e operação logística.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><FileText className="h-4 w-4"/>Novo relatório</button></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={<TrendingUp/>} label="Perdas prevenidas" value="R$ 38.450" sub="Este mês"/><Kpi icon={<ShieldCheck/>} label="Acurácia PEPS" value="99,4%" sub="Conformidade de lote"/><Kpi label="Ruptura nos pontos" value="1,8%" sub="Meta: 2,5%"/><Kpi label="Valor em estoque" value="R$ 412.890" sub="6 unidades integradas"/></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((report)=><article key={report.id} className="flex flex-col rounded-xl border border-slate-200 bg-white p-5 shadow-xs"><span className="w-fit rounded border border-blue-100 bg-blue-50 px-2 py-1 text-[10px] font-bold tracking-wide text-blue-700">{report.badge}</span><h2 className="mt-3 font-bold text-slate-900">{report.title}</h2><p className="mt-1 min-h-10 text-sm leading-relaxed text-slate-500">{report.description}</p><div className="my-4 grid grid-cols-2 gap-3 rounded-lg border border-slate-100 bg-slate-50 p-3"><div><p className="text-[10px] font-semibold uppercase text-slate-400">{report.metricLabel}</p><p className="mt-1 text-sm font-bold text-slate-800">{report.metric}</p></div><div><p className="text-[10px] font-semibold uppercase text-slate-400">{report.secondaryLabel}</p><p className="mt-1 text-sm font-bold text-blue-700">{report.secondaryMetric}</p></div></div><div className="mt-auto flex gap-2 border-t border-slate-100 pt-3"><button type="button" onClick={()=>window.print()} className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-slate-200 bg-white py-2 text-xs font-semibold text-slate-700"><Download className="h-3.5 w-3.5"/>Imprimir / PDF</button><button type="button" className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-blue-50 py-2 text-xs font-semibold text-blue-700"><ArrowRight className="h-3.5 w-3.5"/>Abrir relatório</button></div></article>)}</section></div>;
}
function Kpi({icon,label,value,sub}:{icon?:ReactNode;label:string;value:string;sub:string}){return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-xs font-semibold uppercase text-slate-500">{label}<span className="h-4 w-4 text-blue-600">{icon}</span></div><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{sub}</p></article>}
