import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CreditCard, Search, ShoppingCart, Wallet } from "lucide-react";
import { operationsService } from "../services/operations.service";
import { useLocationFilter } from "../contexts/LocationFilterContext";
import type { SaleTransaction } from "../types/operations";
const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" });
const date = new Intl.DateTimeFormat("pt-BR", { dateStyle:"short", timeStyle:"short" });
export default function Vendas() {
  const [items,setItems]=useState<SaleTransaction[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState("ALL");
  const { matchesLocation } = useLocationFilter();
  useEffect(()=>{void operationsService.listSales().then(setItems);},[]);
  const filtered=useMemo(()=>items.filter((sale)=>matchesLocation(sale.location)).filter((sale)=>(status==="ALL"||sale.status===status)&&`${sale.receipt} ${sale.location} ${sale.items} ${sale.payment}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))),[items,search,status,matchesLocation]);
  const complete=filtered.filter(x=>x.status==="COMPLETED"); const revenue=complete.reduce((sum,x)=>sum+x.total,0);
  return <div className="min-w-0 space-y-6 p-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Vendas · Transações</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Vendas e transações</h1><p className="mt-1 text-sm text-slate-500">Acompanhe o faturamento e as vendas registradas nos pontos de venda.</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><Card icon={<Wallet/>} title="Faturamento filtrado" value={money.format(revenue)}/><Card icon={<ShoppingCart/>} title="Transações concluídas" value={String(complete.length)}/><Card icon={<CreditCard/>} title="Ticket médio" value={money.format(complete.length?revenue/complete.length:0)}/></div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-900">Registro de vendas</h2><p className="mt-1 text-xs text-slate-500">Movimentação recente recebida dos pontos de venda.</p></div><span className="text-xs text-slate-400">Baixa de estoque pelo PEPS</span></div>
    <div className="flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input aria-label="Buscar vendas" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar recibo, unidade ou item" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm"/></div><select aria-label="Filtrar status" value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="ALL">Todos os status</option><option value="COMPLETED">Concluídas</option><option value="REVERSED">Estornadas</option></select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID / Recibo","Data e hora","Ponto de venda","Itens","Pagamento","Total","Status"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(t=><tr key={t.id}><td className="px-4 py-3 font-mono text-xs font-semibold">{t.receipt}</td><td className="px-4 py-3">{date.format(new Date(t.date))}</td><td className="px-4 py-3">{t.location}</td><td className="px-4 py-3">{t.items}</td><td className="px-4 py-3">{t.payment}</td><td className="px-4 py-3 text-right font-semibold">{money.format(t.total)}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${t.status==="COMPLETED"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{t.status==="COMPLETED"?"Concluída":"Estornada"}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-sm text-slate-500">Nenhuma venda corresponde aos filtros.</p>}</div></section></div>;
}
function Card({icon,title,value}:{icon:ReactNode;title:string;value:string}){return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-xs font-semibold uppercase text-slate-500">{title}<span className="h-4 w-4 text-blue-600">{icon}</span></div><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>}
